## This redirects to other doc branches

[[redirects]]
  from = "/ts7.feb.cl/*"
  to = "https://cloud-docs.thoughtspot.com/:splat"
  status = 200
  force = true # COMMENT: ensure that we always redirect
