destination: _site/
url: "http://127.0.0.1:4010"
baseurl: ""
port: 4010
output: pdf
product: mydoc
print_title: Thoughtspot Doc
print_subtitle: Version 4.4
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true

pdf_sidebar: mydoc_sidebar
